### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by wxcafe** [im-tomu/tomu-bootloader#7]
There should probably be *some* documentation, for how to build, flash, and modify the bootloader, maybe about how it works too.

**Comment by mithro** [comment]
The currently used bootloader is [AN0042](https://www.silabs.com/Support%20Documents/TechnicalDocs/AN0042.pdf)

There is some information in Josh's getting started guide at https://groups.google.com/forum/#!topic/tomu-discuss/r-LS0C7hjko

Currently, I believe no-one has been able to successfully build the bootloader with gcc.

**Comment by notthetup** [comment]
It seems that with the latest Simplicity Studio IDE from SiLabs, one can build AN0042 bootloader (now version 1.2) for EFM32HG309. It's quite straight forward. I haven't flashed it in yet though.

Is the code for the two changes from the original documented somewhere?

> - Use internal oscillator rather than requiring an external Crystal (which doesn't exist on the Tomu).
> - Always enter the bootloader, not needing the a pullup on the 'C' pin


For the pin C pullup I'm guess it's changing this line of code.

https://github.com/im-tomu/tomu-bootloader/blob/master/an0042_efm32/src/main.c#L132

**Comment by mithro** [comment]
I think you can build the project with Simplicity Studio IDE fine, the problem is that without the commercial compiler the output is too large.

The source code already has the internal oscillator change. 

As we couldn't build a new binary, the always entering the bootloader was done by patching the bin directly.

**Comment by mithro** [comment]
@notthetup If you can figure out a way to build a working bootloader with free (as in beer) stuff and publish instructions, I'll send you a tomu board (if you don't already have one).

**Comment by notthetup** [comment]
Interesting.. The target BL size is 4K right? 

I have been trying to get USB CDC running on my board (also EFM32HG but not a tomu) but in the application. I still use this USART-USB Bootloader. So I managed to compile some subset of AN00042 on gcc+Makefiles. The compiled binary is indeed large.

I wonder what Simplicity Studio does since AFAIK it uses gcc in the back, that allows the sources to be so little.

**Comment by mithro** [comment]
I'm pretty sure it only compiles small enough when you have the proprietary compiler installed?

**Comment by xobs** [comment]
AN0042 is 16 kB large.

The DFU Bootloader is just a hair over 4 kB, and should be better documented.

**Comment by mithro** [comment]
\o/ 

![party](https://user-images.githubusercontent.com/21212/35184002-726bcd38-fe43-11e7-9275-74e6327a3f89.gif)

**Comment by notthetup** [comment]
@xobs Have you already started working on the DFU port? Is it on github?

**Comment by xobs** [comment]
It's in the toboot/ directory

**Comment by notthetup** [comment]
Ooops. Just realised that it's all done. So I deleted my comment. Thanks! 👍
